{
 "title": "Prediction Drift",
 "time": { "from": "2022-01-30T17:00:00.000Z", "to": "2022-02-28T17:00:00.000Z" },
 "panels": [
  {
   "title": "Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, $__time(\"timestamp\") FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Share Missing Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT share_missing_val, $__time(\"timestamp\") FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT prediction_drift, $__time(\"timestamp\") FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}